baseURL = 'https://ashutosh049.github.io'
title = 'Microlean'
languageCode = 'en-us'
theme = "hugo-theme-cleanwhite-rsy"

paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/home_header_banner.jpeg"
  title = "Software Engineering"
  slogan = "$ grep -rni \"The how's and why's\" ."
  SEOTitle = "Ashutosh's Blog"
  keyword = "Rich, Youngkin, Raspberry, Pi, Docker, Kubernetes, Go, Golang, Microservice"
 
  # Sidebar settings
  sidebar_about_description = "Aspiring Software Artist, Open Source Contributor , Microservice, Cloud Native and DDD Practitioner"
  sidebar_avatar = "images/avatars/profile.jpeg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "ashutosh049@outlook.com"
  linkedin       = "https://www.linkedin.com/in/ashutosh049"
  github         = "https://github.com/ashutosh049"
  medium         = "https://medium.com/@ashutosh049"
  stackoverflow  = "https://stackoverflow.com/users/5324721/kumar-ashutosh"